version: '3'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: sige
      POSTGRES_PASSWORD: pass
    volumes:
      - ./database:/var/lib/postgresql/data
  gunicorn:
    image: versailles
    command: gunicorn -b 0.0.0.0:8000 versailles.wsgi:application
    environment:
      - SECRET_KEY=0#pny4oox9s#+#5dkde25dj79b-o^sdbz4kiumg#e1qx3ky
      - ALLOWED_HOSTS='gunicorn'
      - DATABASE_URL=postgres://sige:pass@postgres/sige
    volumes:
      - ./:/opt/djangoSIGE/
    links:
      - postgres
    working_dir: /opt/djangoSIGE/
  nginx:
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./versailles/static/:/opt/djangoSIGE/static/
      - ./versailles/media/:/opt/djangoSIGE/media/
    ports:
      - 80:80
    links:
      - gunicorn
